# Generated by Django 4.1.5 on 2023-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_topic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.FileField(upload_to='media/'),
        ),
    ]
