# Generated by Django 4.1.5 on 2023-06-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230620_1909'),
        ('main', '0005_chapter_topic_chapter'),
    ]

    operations = [
    ]
